/// Nigerian states and their cities/towns
class NigeriaLocations {
  static const Map<String, List<String>> statesAndCities = {
    'Abia': [
      'Aba',
      'Umuahia',
      'Arochukwu',
      'Ohafia',
      'Bende',
      'Isiala Ngwa',
      'Osisioma',
    ],
    'Adamawa': [
      'Yola',
      'Jimeta',
      'Mubi',
      'Numan',
      'Ganye',
      'Gombi',
    ],
    'Akwa Ibom': [
      'Uyo',
      'Eket',
      'Ikot Ekpene',
      'Oron',
      'Abak',
      'Ikot Abasi',
    ],
    'Anambra': [
      'Awka',
      'Onitsha',
      'Nnewi',
      'Ekwulobia',
      'Agulu',
      'Ihiala',
    ],
    'Bauchi': [
      'Bauchi',
      'Azare',
      'Misau',
      'Jama\'are',
      'Katagum',
    ],
    'Bayelsa': [
      'Yenagoa',
      'Brass',
      'Ogbia',
      'Sagbama',
      'Nembe',
    ],
    'Benue': [
      'Makurdi',
      'Gboko',
      'Otukpo',
      'Katsina-Ala',
      'Vandeikya',
    ],
    'Borno': [
      'Maiduguri',
      'Biu',
      'Bama',
      'Dikwa',
      'Monguno',
    ],
    'Cross River': [
      'Calabar',
      'Ugep',
      'Ikom',
      'Ogoja',
      'Obudu',
    ],
    'Delta': [
      'Asaba',
      'Warri',
      'Sapele',
      'Ughelli',
      'Agbor',
      'Kwale',
    ],
    'Ebonyi': [
      'Abakaliki',
      'Afikpo',
      'Onueke',
      'Ezza',
      'Ishielu',
    ],
    'Edo': [
      'Benin City',
      'Auchi',
      'Ekpoma',
      'Uromi',
      'Ubiaja',
    ],
    'Ekiti': [
      'Ado-Ekiti',
      'Ikere',
      'Ijero',
      'Ikole',
      'Emure',
    ],
    'Enugu': [
      'Enugu',
      'Nsukka',
      'Agbani',
      'Awgu',
      'Oji River',
    ],
    'FCT': [
      'Abuja',
      'Gwagwalada',
      'Kubwa',
      'Kuje',
      'Bwari',
      'Nyanya',
      'Lugbe',
      'Maitama',
      'Wuse',
      'Garki',
      'Asokoro',
      'Gwarinpa',
    ],
    'Gombe': [
      'Gombe',
      'Kumo',
      'Deba',
      'Billiri',
      'Kaltungo',
    ],
    'Imo': [
      'Owerri',
      'Orlu',
      'Okigwe',
      'Mbaise',
      'Oguta',
    ],
    'Jigawa': [
      'Dutse',
      'Hadejia',
      'Gumel',
      'Kazaure',
      'Ringim',
    ],
    'Kaduna': [
      'Kaduna',
      'Zaria',
      'Kafanchan',
      'Kagoro',
      'Saminaka',
    ],
    'Kano': [
      'Kano',
      'Wudil',
      'Gwarzo',
      'Bichi',
      'Rano',
    ],
    'Katsina': [
      'Katsina',
      'Daura',
      'Funtua',
      'Malumfashi',
      'Dutsin-Ma',
    ],
    'Kebbi': [
      'Birnin Kebbi',
      'Argungu',
      'Yauri',
      'Zuru',
      'Jega',
    ],
    'Kogi': [
      'Lokoja',
      'Okene',
      'Kabba',
      'Idah',
      'Ankpa',
    ],
    'Kwara': [
      'Ilorin',
      'Offa',
      'Omu-Aran',
      'Jebba',
      'Lafiagi',
    ],
    'Lagos': [
      'Ikeja',
      'Lagos Island',
      'Ikorodu',
      'Epe',
      'Badagry',
      'Victoria Island',
      'Lekki',
      'Ajah',
      'Surulere',
      'Yaba',
      'Apapa',
      'Festac',
      'Mushin',
      'Oshodi',
      'Alimosho',
      'Agege',
      'Isolo',
      'Ejigbo',
    ],
    'Nasarawa': [
      'Lafia',
      'Keffi',
      'Akwanga',
      'Nasarawa',
      'Doma',
    ],
    'Niger': [
      'Minna',
      'Bida',
      'Kontagora',
      'Suleja',
      'Lapai',
    ],
    'Ogun': [
      'Abeokuta',
      'Ijebu-Ode',
      'Sagamu',
      'Ilaro',
      'Ota',
      'Sango',
    ],
    'Ondo': [
      'Akure',
      'Ondo',
      'Owo',
      'Ikare',
      'Ore',
    ],
    'Osun': [
      'Osogbo',
      'Ile-Ife',
      'Ilesa',
      'Ede',
      'Iwo',
    ],
    'Oyo': [
      'Ibadan',
      'Ogbomoso',
      'Oyo',
      'Iseyin',
      'Saki',
    ],
    'Plateau': [
      'Jos',
      'Bukuru',
      'Pankshin',
      'Shendam',
      'Langtang',
    ],
    'Rivers': [
      'Port Harcourt',
      'Obio-Akpor',
      'Eleme',
      'Okrika',
      'Bonny',
      'Degema',
    ],
    'Sokoto': [
      'Sokoto',
      'Tambuwal',
      'Gwadabawa',
      'Wurno',
      'Goronyo',
    ],
    'Taraba': [
      'Jalingo',
      'Wukari',
      'Bali',
      'Gembu',
      'Ibi',
    ],
    'Yobe': [
      'Damaturu',
      'Potiskum',
      'Gashua',
      'Nguru',
      'Geidam',
    ],
    'Zamfara': [
      'Gusau',
      'Kaura Namoda',
      'Talata Mafara',
      'Bungudu',
      'Anka',
    ],
  };

  static List<String> get states => statesAndCities.keys.toList()..sort();

  static List<String> getCities(String state) {
    return statesAndCities[state] ?? [];
  }
}
